### ISSUE TITLE
I can't start the simulator

### ISSUE THREAD

**Issue by albertosaurio65** [perpetualKid/ORTS-MG#103]
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/8119614/OpenRailsLog.txt)

I choose everything correctly and after a while on the loading screen of the route this error appears
![Captura](https://user-images.githubusercontent.com/70109413/155204700-73f95ac4-3a4c-4d1a-af79-f470dcf04931.JPG)

I have all the requirements, it only happens to me with some trains or routes, in this case it happens to me with the train, if I try another one it works

**Comment by albertosaurio65** [comment]
cabin textures are also moved, which in the OR new year versions look good

**Comment by albertosaurio65** [comment]
and the generic animations 1 and 2 are in continuous loop with respect to the speed of the train

**Comment by perpetualKid** [comment]
seems the error is related to ETCS and in-cab instruments, which explains why only certain trains/routes may be affected. Does the error happen with OR (not OR NewYear) also?

**Comment by perpetualKid** [comment]
no longer relevant since ETCS is using different font rendering now.
