### ISSUE TITLE
Help wanted Unhandled exception 1.3 mono game

### ISSUE THREAD

**Issue by Saikatsaha1996** [perpetualKid/ORTS-MG#105]
![Screenshot_2022-06-24-10-45-05-427_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/175467168-c65e2ed4-f243-4f22-bd1e-f22fa670ebe3.jpg)

![Screenshot_2022-06-24-11-02-40-878_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/175468980-73941057-65da-4268-9dfd-23d996829a6b.jpg)

**Comment by perpetualKid** [comment]
Thanks for reporting. I see that you are using an pretty old version, would you mind upgrading to a recent version please (either using the built-in updater, or manually downloading a newer release). While the issue may still be around in newer versions as well, it will be easier to investigate, and any potential fixes will only be applied to the current codebase.

**Comment by Saikatsaha1996** [comment]
> Thanks for reporting. I see that you are using an pretty old version, would you mind upgrading to a recent version please (either using the built-in updater, or manually downloading a newer release). While the issue may still be around in newer versions as well, it will be easier to investigate, and any potential fixes will only be applied to the current codebase.

Which softwares are dependency?..

Can you give me list for https://github.com/perpetualKid/ORTS-MG/tree/v1.4.4 version?

**Comment by perpetualKid** [comment]
> Which softwares are dependency?..
> 
> Can you give me list for https://github.com/perpetualKid/ORTS-MG/tree/v1.4.4 version?

I'm not sure what dependencies you are referring to ORTS, if you want to play a newer version, please download the latest release 1.4.8 here https://github.com/perpetualKid/ORTS-MG/releases/tag/v1.4.8, it only needs to unzip and run from the unzipped Program folder.

If you want to build from sources yourself, you'll need Visual Studio 2022.

**Comment by Saikatsaha1996** [comment]
> > Which softwares are dependency?..
> > Can you give me list for https://github.com/perpetualKid/ORTS-MG/tree/v1.4.4 version?
> 
> I'm not sure what dependencies you are referring to ORTS, if you want to play a newer version, please download the latest release 1.4.8 here https://github.com/perpetualKid/ORTS-MG/releases/tag/v1.4.8, it only needs to unzip and run from the unzipped Program folder.
> 
> If you want to build from sources yourself, you'll need Visual Studio 2022.

No no i don't need to build , i just need to plug & play..

Actually this is wine that's why i am asking.. 

.net fremwork version?
Dx9 supported?

**Comment by perpetualKid** [comment]
please see the wiki https://github.com/perpetualKid/ORTS-MG/wiki/Linux-Wine 

1.4.4 or 1.4.8 both run on DotNet Core 3.1 (https://dotnet.microsoft.com/en-us/download/dotnet/3.1)

If this is running Linux/Wine, the RailDriver may not work (referring to the initial post, which seems to indicate some issue with the RailDriver implementation), I haven't heard of anyone running on Wine with RailDriver

**Comment by Saikatsaha1996** [comment]
> please see the wiki https://github.com/perpetualKid/ORTS-MG/wiki/Linux-Wine
> 
> 1.4.4 or 1.4.8 both run on DotNet Core 3.1 (https://dotnet.microsoft.com/en-us/download/dotnet/3.1)
> 
> If this is running Linux/Wine, the RailDriver may not work (referring to the initial post, which seems to indicate some issue with the RailDriver implementation), I haven't heard of anyone running on Wine with RailDriver

Ohh that's why not opening..
Actually my system wine windows 10
![Screenshot_2022-06-24-17-59-51-500_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/175536540-dd8bdc4b-c3b3-482a-8120-25cae489ff16.jpg)

So need to install.net core

Actually it is wine 6.0
Host - android 12
Processor SDM 865
GPU adreno 650
Official 1.2 Openrail working fine on wine 7.1

So i am useing wine 6.0 for bug less GPU driver..
Wine 6.0 official 1.2 not running.. only running 1.4..

That's why I want to try latest version openrail MG edition

**Comment by Saikatsaha1996** [comment]
> please see the wiki https://github.com/perpetualKid/ORTS-MG/wiki/Linux-Wine
> 
> 1.4.4 or 1.4.8 both run on DotNet Core 3.1 (https://dotnet.microsoft.com/en-us/download/dotnet/3.1)
> 
> If this is running Linux/Wine, the RailDriver may not work (referring to the initial post, which seems to indicate some issue with the RailDriver implementation), I haven't heard of anyone running on Wine with RailDriver

I don't know why game not opening 
Directx 12 installed
Dotnet core 3.1 full installed
Dot net fremwork 4 + installed
C++ upto 2022 all installed
Java runtime installed
Mono installed

But game still now not opening 😞

**Comment by Saikatsaha1996** [comment]
> I'm not sure if anyone has tried such configuration before, you may be on your own. What system is that running Android 12, I doubt there is an appropriate graphic adapter.

Openrail official 1.2 working in wine 🍷 7.1..
But wine 🍷 7.1 graphics driver have too much bugs and slow that's why I am using 🍷 6.0 .. but my bad luck in wine 🍷 6.0 openrail 1.2 not working.. that why i am trying to install openrail mg version.. but getting same error..


Host device - `android mobile`
Os version - `android 12`
Host processor - `snapdragon 865 (aarch64)`
Host GPU - `Adreno 650`

![Screenshot_2022-06-20-17-45-54-984_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/175636833-2e232f4b-90f2-4c9b-a48b-181ad56bdcc6.jpg)
![Screenshot_2022-06-22-11-08-25-207_com ludashi benchmark](https://user-images.githubusercontent.com/72664192/175636939-f9b3bfb9-467b-412b-94c9-ecf3a8aee610.jpg)

**Comment by Saikatsaha1996** [comment]
@perpetualKid yes performance is obviously not good.. but yes openrail 1.2 working on android mobile with armv8-a architecture..

My bad luck i can't share video with you.. 😞

**Comment by Saikatsaha1996** [comment]
@perpetualKid  finally `menu.exe` opening but instantly crashed..

https://pastebin.com/AaL4aZEJ

Any solution for this ?

**Comment by Saikatsaha1996** [comment]
@perpetualKid  Finally 😃 1.8.11V openrail running in my Android with native Box64 + wine

![IMG_20240218_231642](https://github.com/perpetualKid/FreeTrainSimulator/assets/72664192/3c62611a-c314-4c57-b007-bb9324a1e2dd)
