### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by alifatico1** [perpetualKid/ORTS-MG#121]
Good morning.
We haven't been able to use your version of Open Rails for a long time because when we press the Ctrl+9 key combination to open the Dispatcher (necessary for traffic control in Multiplayer), an error appears and the program crashes.
The version we use is 1.4.13-dev. 35.
I assume you are aware of this problem.
Thank you for your effort.
Kind regards
Pedro

**Comment by perpetualKid** [comment]
do you happen to have a log please? I've tested both multiplayer and single player mode, and can open the Dispatcher just fine, so trying to understand where it may be failing for you. @alifatico1

**Comment by alifatico1** [comment]
[Open Rails Toolbox Log.txt](https://github.com/perpetualKid/ORTS-MG/files/10706215/Open.Rails.Toolbox.Log.txt)
![Error Ultimate](https://user-images.githubusercontent.com/120276327/218066482-d3195cfc-4b86-44f5-b68d-21a0f4cd77f2.jpg)

**Comment by perpetualKid** [comment]
the logfile shared is for Toolbox, not an Activity Run.
Looks like you're using Marias Pass route from MSTS, which activity are you trying to run?

**Comment by alifatico1** [comment]
I have changed my route, one for Open rails.
Now the error does not appear but the game crashes anyway.
I send you the log.
Thank you
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/10706387/OpenRailsLog.txt)

**Comment by alifatico1** [comment]
However, this does not give an error.

Thank you
![Sin error](https://user-images.githubusercontent.com/120276327/218072687-ca844d2a-e674-4ad4-a174-4c7335f05d0b.jpg)
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/10706482/OpenRailsLog.txt)

**Comment by perpetualKid** [comment]
> [Open Rails Toolbox Log.txt](https://github.com/perpetualKid/ORTS-MG/files/10706215/Open.Rails.Toolbox.Log.txt) ![Error Ultimate](https://user-images.githubusercontent.com/120276327/218066482-d3195cfc-4b86-44f5-b68d-21a0f4cd77f2.jpg)

in this screenshot, it looks like the F9 Dispatcher Window is minimized in the top left corner, and it may be the case that the window size settings stored in registry are somehow corrupt, which would explain the error message about invalid number format. 

If still happening, can you please use the registry editor in windows (RegEdit.exe) and delete dispatcher settings under ORTS, so next time Dispatcher will start with default settings. Just navigate to Computer\HKEY_Current_User\Software\OpenRails\ORTS and delete the whole "Dispatcher" key:

![image](https://user-images.githubusercontent.com/7158903/218250316-86a215de-ad36-4289-83e0-5d4706243b6b.png)

**Comment by alifatico1** [comment]
Indeed, just by deleting the Dispacher branch from the windows registry, when you restart open and press Ctrl+9 the new dispatcher appears.
Thanks for the help.
One question, is there no way to run the old dispatcher again?
Thanks again.
Pedro
![Dispacher View](https://user-images.githubusercontent.com/120276327/218253078-2a9cde98-be51-43ac-9aca-f11f9f2dfb59.jpg)

**Comment by perpetualKid** [comment]
there is no more code from the old dispatcher included, only some multiplayer messaging remains until new multiplayer mode is implemented (however I don't know if any of that remaining is important at all).
What are you missing from old dispatcher, any functionality/feature?

**Comment by alifatico1** [comment]
In simple mode, some players use the See in Game buttons and the ability to send messages to another player.
And I'm looking forward to seeing the dispatcher in multiplayer mode.
![Dispacher](https://user-images.githubusercontent.com/120276327/218266289-0c09c9ed-a3d6-4762-85c6-005090c76abd.jpg)

**Comment by alifatico1** [comment]
In simple mode, some players use the See in Game buttons and the ability to send messages to another player.
And I'm looking forward to seeing the dispatcher in multiplayer mode.
![Dispacher](https://user-images.githubusercontent.com/120276327/218268183-06d98423-48a2-406f-8db3-1f66dd2ecbb3.jpg)

**Comment by perpetualKid** [comment]
I could have a look about the "See in game" functionality, but messaging will only be in game until new multiplayer functionality is  worked on, sorry.

Funny side node, I'm planning to visit the place just shown on your map (Berguen) in a few weeks...

I think we can close this original issue now?
