### ISSUE TITLE
Progressbar not showing in fullscreen mode while loading

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/ORTS-MG#13]
Load screen progressbar becomes invisible while running in fullscreen mode. This seem to depend on screen resolution.

**Comment by tassoman** [comment]
Loading bar is visible but looks like 1px height.
I suggest changing its color on something brighter and getting thicker.

**Comment by perpetualKid** [comment]
> Loading bar is visible but looks like 1px height.
> I suggest changing its color on something brighter and getting thicker.

@tassoman there seem some dependency to screen resolution - in FullHD looks like a 1px bar, in smaller resolutions it gets back to the original size, while at larger (4k) there is no loading bar at all visible.
