### ISSUE TITLE
System.IO failed to detect player locomotive.

### ISSUE THREAD

**Issue by Train0814** [perpetualKid/ORTS-MG#131]
When i am running it on Explorer mode everything shows up but activity mode just doesnt load

**Comment by perpetualKid** [comment]
please provide more details, such as logfile and screenshots. The issue you are raising is so unspecific that there is nothing anyone can do about without any more details

**Comment by Train0814** [comment]
Here is the issue .
![Problem](https://github.com/perpetualKid/ORTS-MG/assets/149865328/b5625b7d-1cdb-47ae-8224-3fb03fca2f5e)
the explorer mode loads up my consists , but as i switch the game mode to Activity , it crashes

**Comment by perpetualKid** [comment]
if you look at the error message it states there is no player locomotive found in the activity, so I suggest to go back to the author of the activity to ask for an update there. There is nothing the program can do about. 
In Explorer Mode, player locomotive will be freely selected from the available.

**Comment by Train0814** [comment]
But while playing in other older versions of Open Rails , it worked just fine.

**Comment by perpetualKid** [comment]
please update to a recent version. 1.4.3 as shown in the screenshot is about 2 years old
