### ISSUE TITLE
Head and rear lights of trains get delayed on increasing velocity

### ISSUE THREAD

**Issue by nfsprodriver** [perpetualKid/ORTS-MG#15]
In the Monogame version of ORTS I currently have the issue, that the head and rear light are positionally delayed from the train. The higher the velocity of the train the bigger is the distance of the lights.

**Comment by perpetualKid** [comment]
fixed in 1.3.1-187-0ca403bad

**Comment by perpetualKid** [comment]
updated fix in 1.3.1-188-311f9b1
