### ISSUE TITLE
Updater fails when files/folder still in use

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/ORTS-MG#16]
The updater fails with an error message if files or subfolders are still opened somewhere

**Comment by HengYeDev** [comment]
This is very important for Linux, as it seems that in wine the file is always held by the wine process.

**Comment by perpetualKid** [comment]
if the updater is causing to much struggle, we could just offer the direct download link as well so users may manually download and unpack.

**Comment by perpetualKid** [comment]
can't get solved unless running updater code out of band i.e. from temp directory.
