### ISSUE TITLE
Sliding Wheels On Diesel locomotives. 

### ISSUE THREAD

**Issue by ParkerBoots** [perpetualKid/ORTS-MG#25]
[OpenRailsLog.txt](https://github.com/perpetualKid/ORTS-MG/files/4513627/OpenRailsLog.txt)

Diesel locomotive wheels do not turn, and can cause errors on bootup.

**Comment by perpetualKid** [comment]
If I remember right, there was a similar issue in offical OR, will need to dig and merge any updates.

**Comment by perpetualKid** [comment]
This should be solved. If still experiencing issues, please provide details to reproduce.
