### ISSUE TITLE
Drop .NET Framework 4.8 and use .NET Core 3.1 only

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/ORTS-MG#41]
see https://github.com/perpetualKid/ORTS-MG/wiki/.NET-Framework

**Comment by perpetualKid** [comment]
WIP 9b5866514f097e9f142af355773a9a008a74af04

**Comment by perpetualKid** [comment]
RailDriver is using PIEHid32Net/PIEHid64Net dlls which are build in .NET FX. While running fine in .NET Core, this is a dependency to have .NET FX installed. May be an issue mostly for non-Windows systems for the time being. Investigate moving te PIEHid*Net to .NET Core.

**Comment by perpetualKid** [comment]
> RailDriver is using PIEHid32Net/PIEHid64Net dlls which are build in .NET FX. While running fine in .NET Core, this is a dependency to have .NET FX installed. May be an issue mostly for non-Windows systems for the time being. Investigate moving te PIEHid*Net to .NET Core.

RailDriver solved with new .NET Standard Raildriver package

**Comment by HengYeDev** [comment]
seems done in latest release?
