### ISSUE TITLE
Screenshot has some defects

### ISSUE THREAD

**Issue by HengYeDev** [perpetualKid/ORTS-MG#54]
There's some differences and the built in screenshot doesn't look as good and has some problems in terms of lighting.
Taken with built in: 
![image](https://user-images.githubusercontent.com/62600441/112335033-44a96c80-8c92-11eb-8e7f-6ee7e22eb83b.png)
The lighting in the carriage looks a bit off...
Compared with one taken with the default screenshot tool (from kde)
![image](https://user-images.githubusercontent.com/62600441/112335492-a9fd5d80-8c92-11eb-98be-ce93e2035cde.png)

**Comment by perpetualKid** [comment]
I've a hard time to understand the differences, can you share some screenshots taken from a same train and perspective?

**Comment by HengYeDev** [comment]
Sure, but for those images, look in the windows

**Comment by perpetualKid** [comment]
which version are you using now? There's been some change to the screenshot code recently, as of 1.3.6-ci.20 (https://github.com/perpetualKid/ORTS-MG/issues/37), so you may try some version before or after to see if there is a difference

**Comment by perpetualKid** [comment]
@HengYeDev give it a try when you got some cycles

**Comment by HengYeDev** [comment]
can no longer repro. thanks
