### ISSUE TITLE
Screnshots for Activity Save are broken

### ISSUE THREAD

**Issue by perpetualKid** [perpetualKid/ORTS-MG#58]
![image](https://user-images.githubusercontent.com/62600441/112522935-95919180-8d74-11eb-91aa-d6a4abffeaa9.png)

_Originally posted by @HengYeDev in https://github.com/perpetualKid/ORTS-MG/issues/55#issuecomment-807219464_

**Comment by HengYeDev** [comment]
Cannot reproduce issue on 1.3.7-ci.8

**Comment by HengYeDev** [comment]
I'll try to test later, i had big project last week. its fine if you cant reproduce though, make sure to test from different angles...sometimes with the broken ones it worked from some angles.



Heng Ye
https://yeheng.org | Twitter https://twitter.com/HengYeDev








---- On Tue, 06 Apr 2021 03:25:53 -0400 perpetualKid ***@***.***> wrote ----




Closed https://github.com/perpetualKid/ORTS-MG/issues/58.

**Comment by HengYeDev** [comment]
can no longer reproduce thanks.
