### ISSUE TITLE
USB HID controls

### ISSUE THREAD

**Issue by HengYeDev** [perpetualKid/ORTS-MG#73]
It could be possible in the future to enable support for USB HID controls such as flight sim throttles.

**Comment by perpetualKid** [comment]
indeed, this is what the work on #47 was about, to implement some framework to allow differnt kind of input mapped to actions in the program, to handle and control train behavior. Keyboard and Mouse input are not refactored to this new approach, and #70 is work in progress for [RailDriver](https://www.raildriver.com) input. I'm tempted to implement Gamepad support as well, but this will be lower priority. 
Other custom/proprietary controls could be implemented following same pattern if there is a need or someone picking up that task.

I think this is more appropriate in discussions for now as this is not an open issue really?
