### ISSUE TITLE
A bug when selecting Timetable Mode

### ISSUE THREAD

**Issue by mateusz-fortuna** [perpetualKid/ORTS-MG#96]
**First exception data:**
[first exception.txt](https://github.com/perpetualKid/ORTS-MG/files/7576249/first.exception.txt)

**The second log was not generated**

![1](https://user-images.githubusercontent.com/58860005/142761995-e812d1e9-7430-4035-820d-4b33e0fa0a22.jpg)
![2](https://user-images.githubusercontent.com/58860005/142762004-0062108b-d398-44fa-bab0-050b1a4b8f61.jpg)

**Comment by perpetualKid** [comment]
Fix available in developer update channel 1.4.4-dev.6

btw nice route, is that available for download somewhere?

**Comment by mateusz-fortuna** [comment]
Thank you for the fix.

Link to the route: https://or.trainsim.pl/Pliki_strony/Download/Trasy/OR_E30.zip
Timetable: https://drive.google.com/file/d/1kPdh8mgkZuRwQKF_mpw7O0ARuITatwzx/view?usp=sharing

Other interesting Polish routes you can find there:
https://or.trainsim.pl/download/trasy/

![Screenshot 2021-11-21 210007](https://user-images.githubusercontent.com/58860005/142777036-5143aca2-869c-408f-a8b2-3d0f9882fc1b.jpg)
