### ISSUE TITLE
Invalid game save

### ISSUE THREAD

**Issue by mateusz-fortuna** [perpetualKid/ORTS-MG#99]
I pressed the F2 key. The game was closed, and I got the following error:

![1](https://user-images.githubusercontent.com/58860005/145459815-4ab321bc-df75-4728-8c51-7e68158e3e1d.jpg)

I checked if the gameplay was saved. The save does not contain a thumbnail image. When I try to open it, a modal window opens, and I get an information to find the save file. I do not have that file.

![2](https://user-images.githubusercontent.com/58860005/145460618-1fa300c7-20f6-4a5e-a166-4adef3771338.jpg)

**Comment by perpetualKid** [comment]
just to confirm, this is for TimeTable mode, correct?

**Comment by perpetualKid** [comment]
I've just pushed a code change which is available now in developer build 1.4.5-dev.11, but I'm not sure if that addresses your issue also, can you check with a new game please?
The old savepoints are unfortunately not recoverable.

**Comment by perpetualKid** [comment]
sorry, wasn't meant to do so - if you open the "Options" in the menu, and go to the "Updater" tab, you can select the "Developer" channel for updates, which gets you just the latest build:

![image](https://user-images.githubusercontent.com/7158903/145479736-21cc112e-b618-4cd0-886f-d74b949bae5d.png)

**Comment by perpetualKid** [comment]
If you are more generally interested to code and build on your own and need some help, feel free to open a separate thread in the discussion section here in GitHub, or join the Gitter chat

**Comment by mateusz-fortuna** [comment]
Game saving works properly right now. The issue is solved. Thank you so much!

I'm a Typescript developer, but If I want to taste .NET some day, I'll try this project.
